name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get actual patch version
        id: actual_patch_version
        run: echo ::set-output name=ACTUAL_PATCH_VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/v//g')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image to GitHub Package Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64 ,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}